### ISSUE TITLE
Hydro model

### ISSUE THREAD

**Issue by rschell** [adamgreenhall/minpower#11]
Been working with the Hydro branch(s) for the last month, starting to make progress with it.  Need to review the water balance constraint, don't think it is formulated correctly.  I have changed my version to 'volume(t)=volume(t-1)+inflows-net_outflow'.  Also having issues with ramping constraints and the model was missing several net_outflow constraints.  Would like to collaborate more.  BTW your email address needs to be updated, I have been getting delivery errors for "minpower@adamgreenhall.com".

Ronald Schellberg
Idaho Power Company
Transmission Policy and Development

**Comment by BjoernLaemmerzahl** [comment]
What ever happened to your efforts Ronald? :)

**Comment by rschell** [comment]
The hydro model is fully functional and have benchmarked against actual operation, however, I have made numerous other changes that make a push non-trivial exercise.

One example is I have created a time series class that allows the user to supply a fixed number or a time series to a number of fields.  Another is a class to handle piecewise input data.

Ron

**Comment by BjoernLaemmerzahl** [comment]
Hey Ron,

that is great to hear. Obviously the model is incomplete without Hydro/Pump Storage :) Adding a time series class is also something I have written on my To-Do-list to account for unavailable production units and time-varying marginal costs. I have seen you proposed some additions to the Hydro part. I will try to add them this weekend and see how far I can get it to work.

Hopefully you will at some point in the future find the time to show us a minimum example. 

P.s.: You may also find some additional inspiration here: https://github.com/FRESNA/PyPSA

Best Regards,

Björn
