### ISSUE TITLE
Link to main documentation files is broken (Minpowertoolkit.com).

### ISSUE THREAD

**Issue by tj800x** [adamgreenhall/minpower#22]
The Minpowertoolkit.com domain looks like it has been lost to a Japanese marketer.

**Comment by adamgreenhall** [comment]
thanks for the heads up. I [removed the domain forwarding](https://github.com/adamgreenhall/minpower/commit/1553a50d4f2c7c0c95e2d6f55c272b38a3014280) so the documentation start using github pages shortly.
